"""Finding collection and HTML report generation."""
from __future__ import unicode_literals

import os

from jinja2 import Template

SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2, "info": 3}

SEVERITY_COLORS = {
    "high": "#c0392b",
    "medium": "#e67e22",
    "low": "#f1c40f",
    "info": "#2980b9",
}

REPORT_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>CyberSentinel Report - {{ info.host }}</title>
<style>
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0;
         background: #f4f6f8; color: #222; }
  header { background: #1b2a4a; color: #fff; padding: 24px 32px; }
  header h1 { margin: 0 0 4px; font-size: 22px; }
  header .meta { font-size: 13px; opacity: .85; }
  .wrap { max-width: 980px; margin: 24px auto; padding: 0 16px; }
  .summary { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 24px; }
  .chip { background: #fff; border-radius: 8px; padding: 12px 16px; min-width: 90px;
          box-shadow: 0 1px 3px rgba(0,0,0,.08); }
  .chip .n { font-size: 24px; font-weight: 700; }
  .chip .l { font-size: 12px; text-transform: uppercase; letter-spacing: .04em; color: #666; }
  .finding { background: #fff; border-radius: 8px; margin-bottom: 14px;
             box-shadow: 0 1px 3px rgba(0,0,0,.08); overflow: hidden; }
  .finding .bar { padding: 10px 16px; color: #fff; display: flex;
                  justify-content: space-between; align-items: center; }
  .finding .bar .sev { font-size: 11px; text-transform: uppercase; font-weight: 700; }
  .finding .body { padding: 14px 16px; }
  .finding .body p { margin: 6px 0; font-size: 14px; }
  .finding .body .label { color: #666; font-weight: 600; }
  code { background: #eef1f4; padding: 1px 5px; border-radius: 4px;
         word-break: break-all; font-size: 13px; }
  .empty { background: #fff; border-radius: 8px; padding: 28px; text-align: center;
           color: #2e7d32; box-shadow: 0 1px 3px rgba(0,0,0,.08); }
  footer { text-align: center; color: #888; font-size: 12px; margin: 24px 0; }
  .apps { font-size: 13px; color: #555; }
</style>
</head>
<body>
<header>
  <h1>&#128737; CyberSentinel Security Report</h1>
  <div class="meta">
    Target: {{ info.url }} &nbsp;|&nbsp; Host: {{ info.host }}<br>
    Scan date: {{ info.date }} &nbsp;|&nbsp; Duration: {{ info.scan_time }}
    &nbsp;|&nbsp; Pages scanned: {{ info.pages_scanned }}
  </div>
</header>
<div class="wrap">
  {% if info.detected_apps %}
  <p class="apps"><strong>Detected technologies:</strong>
    {% for t, apps in info.detected_apps.items() %}{{ t }}: {{ apps|join(', ') }}{% if not loop.last %} &middot; {% endif %}{% endfor %}
  </p>
  {% endif %}

  <div class="summary">
    {% for sev in ['high','medium','low','info'] %}
    <div class="chip">
      <div class="n" style="color: {{ colors[sev] }}">{{ counts.get(sev, 0) }}</div>
      <div class="l">{{ sev }}</div>
    </div>
    {% endfor %}
  </div>

  {% if findings %}
    {% for f in findings %}
    <div class="finding">
      <div class="bar" style="background: {{ colors.get(f.severity, '#555') }}">
        <span>{{ f.title }}</span>
        <span class="sev">{{ f.severity }}</span>
      </div>
      <div class="body">
        <p><span class="label">URL:</span> <code>{{ f.url }}</code></p>
        {% if f.detail %}<p><span class="label">Detail:</span> {{ f.detail }}</p>{% endif %}
        {% if f.evidence %}<p><span class="label">Evidence:</span> <code>{{ f.evidence }}</code></p>{% endif %}
        {% if f.recommendation %}<p><span class="label">Recommendation:</span> {{ f.recommendation }}</p>{% endif %}
      </div>
    </div>
    {% endfor %}
  {% else %}
    <div class="empty">&#9989; No issues were detected by the checks that ran.</div>
  {% endif %}
</div>
<footer>
  Generated by CyberSentinel &mdash; for authorized security assessment only.
</footer>
</body>
</html>"""


class Log(object):
    """Accumulates findings and scanned URLs, then renders an HTML report."""

    def __init__(self):
        self.findings = []
        self.urls = []

    def add_url(self, url, color=None):
        if url not in self.urls:
            self.urls.append(url)

    def add_finding(self, title, url, severity="info", detail=None,
                    evidence=None, recommendation=None):
        severity = severity.lower()
        if severity not in SEVERITY_ORDER:
            severity = "info"
        self.findings.append(
            {
                "title": title,
                "url": url,
                "severity": severity,
                "detail": detail,
                "evidence": (evidence or "")[:300],
                "recommendation": recommendation,
            }
        )

    # Convenience aliases used by the attack checks.
    def high(self, title, url, **kw):
        self.add_finding(title, url, severity="high", **kw)

    def medium(self, title, url, **kw):
        self.add_finding(title, url, severity="medium", **kw)

    def low(self, title, url, **kw):
        self.add_finding(title, url, severity="low", **kw)

    def info(self, title, url, **kw):
        self.add_finding(title, url, severity="info", **kw)

    def _counts(self):
        counts = {}
        for f in self.findings:
            counts[f["severity"]] = counts.get(f["severity"], 0) + 1
        return counts

    def write_html_report(self, filename, audit_info):
        base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        reports_dir = os.path.join(base, "reports")
        os.makedirs(reports_dir, exist_ok=True)
        out_path = os.path.join(reports_dir, filename)

        info = {
            "url": audit_info.get("url", ""),
            "host": audit_info.get("host", ""),
            "date": audit_info.get("date", "").strftime("%Y-%m-%d %H:%M")
            if hasattr(audit_info.get("date", ""), "strftime")
            else str(audit_info.get("date", "")),
            "scan_time": audit_info.get("scan_time", ""),
            "detected_apps": audit_info.get("detected_apps", {}),
            "pages_scanned": len(self.urls) or 1,
        }

        findings = sorted(
            self.findings, key=lambda f: SEVERITY_ORDER.get(f["severity"], 9)
        )
        html = Template(REPORT_TEMPLATE).render(
            info=info,
            findings=findings,
            counts=self._counts(),
            colors=SEVERITY_COLORS,
        )
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(html)
        return out_path
